# Generated by Django 4.0.4 on 2022-05-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('content', models.TextField(default='')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
